name: ESLint and Prettier

on:
  push:
    branches:
      - master

# defaults:
#   run:
#     working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm install
      - run: npm run lint
      - run: npm run format
